networks:
  local:
    driver: bridge

services:
  ythls-fastapi:
    container_name : ythls-fastapi
    image          : ythls-fastapi:latest
    tty            : true
    restart        : always
    build          : .

    volumes:
      - ./AYAR.yml:/usr/src/ythls-FastAPI/AYAR.yml:ro
      - ./cookies.txt:/usr/src/ythls-FastAPI/cookies.txt
    networks:
      - local
    ports:
      - 8889:3310